jobs:
  test:
    executor:
      name: node/default
      tag: '12.18'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests
      - run:
        command: yarn run lint
orbs:
  node: circleci/node@4.0.0
version: 2.1
workflows:
  test_tech_network_ui:
    jobs:
      - test
